export const data = [
  { id: "clear", label: "C", value: "clear", type: "action" },
  { id: "backspace", label: "⬅", value: "backspace", type: "action" },
  { id: "divide", label: "÷", value: "/", type: "operator" },
  { id: "multiply", label: "×", value: "*", type: "operator" },
  { id: "seven", label: "7", value: "7", type: "number" },
  { id: "eight", label: "8", value: "8", type: "number" },
  { id: "nine", label: "9", value: "9", type: "number" },
  { id: "subtract", label: "−", value: "-", type: "operator" },
  { id: "four", label: "4", value: "4", type: "number" },
  { id: "five", label: "5", value: "5", type: "number" },
  { id: "six", label: "6", value: "6", type: "number" },
  { id: "add", label: "+", value: "+", type: "operator" },
  { id: "one", label: "1", value: "1", type: "number" },
  { id: "two", label: "2", value: "2", type: "number" },
  { id: "three", label: "3", value: "3", type: "number" },
  { id: "equals", label: "=", value: "=", type: "action" },
  { id: "zero", label: "0", value: "0", type: "number" },
  { id: "decimal", label: ".", value: ".", type: "number" },
];
